name: Update README with Hashnode Posts

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch latest posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://java-for-developers.hashnode.dev/rss.xml"
